name: Put data into context.
author: 'MiLaboratories'
description: |
  Put data into context so other jobs can read it later.
  Consider context as key-value store with immutable values.
  Once stored under specific key, the value can not be changed.

  NOTE: for large files use 'cache' GitHub Actions functionality
        as 'context' is based on 'artifacts' and is slow on big files.

inputs:
  key:
    description: |
      The key to use for value storage.
      The value could be retreived from context by this key.
    required: true

  value:
    description: |
      The value to store under key.
    required: true

runs:
  using: "composite"

  steps:
    - id: clean-ctx
      shell: bash
      env:
        CTX_PATH: ${{ github.action_path }}/../ctx

      run: |
        # Clean target ctx directory (just for integrity and safety) and resolve its abs path
        rm -rf "${CTX_PATH}"

        echo "path=$(realpath "${CTX_PATH}")" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@v6
      with:
        name: context
        path: ${{ steps.clean-ctx.outputs.path }}

    - shell: bash
      env:
        CTX_PATH: ${{ steps.clean-ctx.outputs.path }}
        CTX_KEY: ${{ inputs.key }}
        CTX_VALUE: ${{ inputs.value }}

      run: |
        # Put value into context key
        printf "%s" "${CTX_VALUE}" > "${CTX_PATH}/${CTX_KEY}"

    - uses: actions/upload-artifact@v6
      with:
        name: context
        path: ${{ steps.clean-ctx.outputs.path }}
        overwrite: true
