name: Replace text in each line from input
author: 'MiLaboratories'
description: |
  Gets list of lines and treat them with list of replacement rules.
  
  At most one replacement rule is applied to each line.
  Lines not matched to any of replacement rules are returned 'as-is'.

inputs:
  input:
    description: |
      List of strings to treat with replacement rules.
    required: false
    default: ''

  replace-rules:
    description: |
      Text replacement rules in format <match> -> <replace>
      One rule per line.
      
      Empty lines are ignored.

    required: false
    default: ''

outputs:
  result:
    description: |
      Input text treated by replacement rules.

runs:
  using: 'node12'
  main: '../impl/dist/replace-prefixes.js'
