packages:
  - lib/build-configs
  - lib/milib

  - actions/post/shell
  - actions/post/artifact

catalog:
  # Build
  'typescript': ~5.8.3
  'vite': ^7.1.7

  # 'tsconfig-paths': ^4.2.0
  'tsup': ~8.3.5
  'rollup-plugin-node-externals': ^8.0.0
  '@rollup/plugin-node-resolve': ^16.0.1
  # 'rollup-plugin-sourcemaps2': ^0.5.0
  'vite-plugin-dts': ^4.5.3
  # 'tsc-alias': ^1.8.11
  # 'yarpm': ^1.2.0
  # 'ts-node': ^10.9.2

  # # Build util / linters

  '@vercel/ncc': ^0.38.4
  '@changesets/cli': ^2.29.2

  '@typescript-eslint/eslint-plugin': ^8.33.1
  '@typescript-eslint/parser': ^8.33.1
  'eslint': ^9.28.0
  'eslint-plugin-github': ^6.0.0
  'prettier': ^3.6.2

  'turbo': ^2.5.2

  # # Util & other libs

  "@actions/exec": "^1.1.1"
  "@actions/core": "^1.10.0"
  "@actions/github": "^6.0.1"
  "@actions/artifact": "^2.3.2"
  "@actions/glob": "^0.5.0"
  "semver": "^7.6.3"

  # # Test

  'vitest': ^3.2.3
  '@vitest/coverage-v8': ^3.2.3

  # # Types

  '@types/node': ^24.5.2
  '@types/semver': ^7.7.0
