name: Create a .sig with gcloud kms
author: 'MiLaboratories'
description: |
 Auth in GCP, install gcloud cli tool.
 Create a .sig for a given file with the gcloud kms asymmetric-sign.

inputs:

  #
  # File Control
  #
  file-path:
    description: |
      Path to a file to create a .sig for.
    required: false

  #
  # GCP Control
  #
  gcloud-kms-workload-identity-provider:
    description: |
      Tha name of the GCP workload identity federation provider.
    required: false

  gcloud-kms-service-account:
    description: |
      The name of the GCP service account.
    required: false

  gcloud-sdk-version:
    description: |
      Version or version constraint of the gcloud SDK to install. If
      unspecified, it will accept any installed version of the gcloud SDK. If
      set to "latest", it will download the latest available SDK. If set to a
      version constraint, it will download the latest available version that
      matches the constraint. Examples: "290.0.1" or ">= 197.0.1".
    required: false
    default: 'latest'

  gcloud-kms-location:
    description: |
      KMS key and keyring location
    required: false
    default: 'europe-west3'

  gcloud-kms-digest-algorithm:
    description: |
      The algorithm to digest the input.
      Must be one of: sha256, sha384, sha512.
    required: false
    default: 'sha256'

  gcloud-kms-key-version:
    description: |
      Version of KMS key.
    required: false
    default: '1'

  gcloud-kms-keyring:
    description: |
      KMS keyring name in GCP.
    required: false

  gcloud-kms-key-name:
    description: |
      KMS key name in GCP.
    required: false

runs:
  using: "composite"

  steps:
    -  name: Configure GCP credentials
       id: gcp_auth
       uses: google-github-actions/auth@v2
       with:
         workload_identity_provider: ${{ inputs.gcloud-kms-workload-identity-provider }}
         service_account: ${{ inputs.gcloud-kms-service-account }}
         token_format: 'access_token'

    - name: Set up GCloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: ${{ inputs.gcloud-sdk-version }}

    - name: Create sig file
      uses: milaboratory/github-ci/actions/shell@v4-db-1
      env:
        FILE_PATH: ${{ inputs.file-path }}
      with:
        run: |
          FILE_PARENT_PATH="${FILE_PATH%/*}"
          FILE_NAME="${FILE_PATH##*/}"
          FILE_SIG="${FILE_NAME}.sig"

          gcloud kms asymmetric-sign \
              --version ${{ inputs.gcloud-kms-key-version }} \
              --key ${{ inputs.gcloud-kms-key-name }} \
              --keyring ${{ inputs.gcloud-kms-keyring }} \
              --location ${{ inputs.gcloud-kms-location }} \
              --digest-algorithm ${{ inputs.gcloud-kms-digest-algorithm }}\
              --input-file "${FILE_PATH}" \
              --signature-file "${FILE_PARENT_PATH}/${FILE_SIG}"
