name: Run ssh-agent
author: 'MiLaboratories'
description: |
  Run `ssh-agent` and load an SSH key to access other private repositories.
  See original action webfactory/ssh-agent

inputs:
  ssh-private-key:
    description: 'Private SSH key to register in the SSH agent'
    required: true
  ssh-auth-sock:
    description: 'Where to place the SSH Agent auth socket'
  log-public-key:
    description: 'Whether or not to log public key fingerprints'
    required: false
    default: 'true'
  ssh-agent-cmd:
    description: 'ssh-agent command'
    required: false
  ssh-add-cmd:
    description: 'ssh-add command'
    required: false
  git-cmd:
    description: 'git command'
    required: false

runs:
  using: "composite"

  steps:
    - name: Run ssh-agent
      uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
        ssh-auth-sock: ${{ inputs.ssh-auth-sock }}
        log-public-key: ${{ inputs.log-public-key }}
        ssh-agent-cmd: ${{ inputs.ssh-agent-cmd }}
        ssh-add-cmd: ${{ inputs.ssh-add-cmd }}
        git-cmd: ${{ inputs.git-cmd }}