name: Initialize context
author: 'MiLaboratories'
description: |
  Initialize `context` artifact with main run data.
  `context` artifact is used to pass data between jobs and actions.

  This action should be called first in workflow to provide all
  blocks (`blocks/*` actions) with information they require.

inputs:
  branch-versioning:
    description: |
      Put a branch name here to activate simple branch versioning mode
    required: false

  version-canonize:
    description: |
      Canonize version number to make it always look like regular semver: '<major>.<minor>.<patch>'.
      This makes git tag 'v1.1' to produce version '1.1.0' instead of '1.1'.
    required: false
    default: 'true'

  version-fetch-depth:
    description: |
      The number of commits of git history from current HEAD to fetch
    required: false
    default: '200'

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/context/create@v3

    - uses: actions/checkout@v2
    - id: versions
      uses: milaboratory/github-ci/actions/detect-version@v3-beta
      with:
        canonize: ${{ inputs.version-canonize }}
        fetch-depth: ${{ inputs.version-fetch-depth }}
        branch-versioning: ${{ inputs.branch-versioning }}

    - uses: milaboratory/github-ci/actions/context/put@v3
      with:
        key: "versions.json"
        value: ${{ toJSON( steps.versions.outputs ) }}
