name: Initialize context
author: 'MiLaboratories'
description: |
  Initialize `context` artifact with main run data.
  `context` artifact is used to pass data between jobs and actions.

  This action should be called first in workflow to provide all
  blocks (`blocks/*` actions) with information they require.

inputs:
  branch-versioning:
    description: |
      Put a branch name here to activate simple branch versioning mode
    required: false

  version-canonize:
    description: |
      Canonize version number to make it always look like regular semver: '<major>.<minor>.<patch>'.
      This makes git tag 'v1.1' to produce version '1.1.0' instead of '1.1'.
    required: false
    default: 'true'

  version-fetch-depth:
    description: |
      The number of commits of git history from current HEAD to fetch
    required: false
    default: '1000'

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.version-fetch-depth }}
        fetch-tags: true

    - id: versions
      uses: milaboratory/github-ci/actions/detect-version@v4-beta
      with:
        canonize: ${{ inputs.version-canonize }}
        fetch-depth: ${{ inputs.version-fetch-depth }}
        branch-versioning: ${{ inputs.branch-versioning }}

    - id: clean-ctx
      shell: bash
      env:
        CTX_PATH: ${{ github.action_path }}/ctx

      run: |
        # Create clean target ctx directory
        rm -rf "${CTX_PATH}"
        mkdir -p "${CTX_PATH}"

        echo "path=$(realpath "${CTX_PATH}")" >> $GITHUB_OUTPUT

    - shell: bash
      env:
        CTX_PATH: ${{ steps.clean-ctx.outputs.path }}
        CTX_VALUE: ${{ toJson(steps.versions.outputs) }}

      run: |
        # Write context data into file
        printf "%s" "${CTX_VALUE}" > "${CTX_PATH}/context.json"

    - uses: actions/upload-artifact@v6
      with:
        name: context
        path: ${{ steps.clean-ctx.outputs.path }}
        overwrite: false
