name: Get data from context.
author: 'MiLaboratories'
description: |
  Get from context data stored by prevoius jobs.
  Consider context as key-value store with immutable values.
  Once stored under specific key, the value can not be changed.

  NOTE: for large files use 'cache' GitHub Actions functionality
        as 'context' bases on 'artifacts' and is slow on big files.

inputs:
  ignore-missing:
    description: |
      Don't fail on attempt to read missing key from context.
      This affects only action's status on attemt to read missing key.

      Use 'default-value' to control the value returned for
      missing keys and races.
    required: false
    default: 'false'

  default-value:
    description: |
      Default value to return when no key found in context or race detected.
      This does not affect action status for missing keys.

      Use 'ignore-missing' input to control action's status.

    required: false
    default: ''

outputs:
  value:
    description:
      The value loaded from context
    value: ${{ fromJSON(steps.value.outputs.data).value }}

runs:
  using: "composite"

  steps:
    - id: needs_update
      uses: milaboratory/github-ci/actions/shell@v4-beta
      env:
        CTX_PATH: ${{ github.action_path }}/../ctx

      with:
        run: |
          if [ ! -e "${CTX_PATH}" ]; then
            echo 'true'
            exit 0
          fi

          echo 'false'

    - uses: actions/download-artifact@v6
      # There is no 'continue-on-error' in composite actions,
      # that is why we can't make action be 'ok' for absent artifact.
      if: steps.needs_update.outputs.stdout == 'true'
      with:
        name: context
        path: ${{ github.action_path }}/../ctx

    - id: value
      if: always()
      uses: milaboratory/github-ci/actions/shell@v4-beta

      env:
        CTX_PATH: ${{ github.action_path }}/../ctx
        CTX_KEY: ${{ inputs.key }}
        IGNORE_MISSING: ${{ inputs.ignore-missing }}
        DEFAULT_VALUE: ${{ inputs.default-value }}

      with:
        dump-stdout: false
        run: |
          ctx_file="${CTX_PATH}/context.json"

          if [ -r "${ctx_file}" ]; then
            ghwa_set_output 'value' "$(cat "${ctx_file}")"
            exit 0
          fi

          ghwa_set_output 'value' "${DEFAULT_VALUE}"

          if [ "${IGNORE_MISSING}" = "true" ]; then
            exit 0
          else
            ghwa_error "Key '${CTX_KEY}' is missing in context artifact"
            exit 1
          fi
