name: Get data from context.
author: 'MiLaboratories'
description: |
  Get from context data stored by prevoius jobs.
  Consider context as key-value store with immutable values.
  Once stored under specific key, the value can not be changed.

  NOTE: for large files use 'cache' GitHub Actions functionality
        as 'context' bases on 'artifacts' and is slow on big files.

inputs:
  default-value:
    description: |
      Default value to return when no key found in context or race detected.
      This does not affect action status for missing keys.

      Use 'ignore-missing' input to control action's status.

    required: false
    default: ''

outputs:
  value:
    description:
      The value loaded from context
    value: ${{ steps.value.outputs.data }}

runs:
  using: "composite"

  steps:
    - id: needs_update
      uses: milaboratory/github-ci/actions/shell@v4
      env:
        CTX_PATH: ${{ github.action_path }}/../ctx

      with:
        run: |
          if [ ! -e "${CTX_PATH}" ]; then
            echo 'true'
            exit 0
          fi

          echo 'false'

    - uses: actions/download-artifact@v6
      # There is no 'continue-on-error' in composite actions,
      # that is why we can't make action be 'ok' for absent artifact.
      if: steps.needs_update.outputs.stdout == 'true'
      with:
        name: context
        path: ${{ github.action_path }}/../ctx

    - id: value
      if: always()
      shell: bash

      env:
        CTX_PATH: ${{ github.action_path }}/../ctx
        DEFAULT_VALUE: ${{ inputs.default-value }}

      run: |
        # Read context or default value into outputs
        ctx_file="${CTX_PATH}/context.json"

        delimiter="CTXEOF_aim3ohghohh2ohkahfaeq" # unique-enough to never intersect with data

        if [ -r "${ctx_file}" ]; then
          {
            echo "data<<${delimiter}"
            cat "${ctx_file}"
            echo ""
            echo "${delimiter}"
          } >> $GITHUB_OUTPUT
        else
          {
            echo "data<<${delimiter}"
            echo "${DEFAULT_VALUE}"
            echo "${delimiter}"
          } >> $GITHUB_OUTPUT
        fi
