name: 'Install AWS CLI'
description: |
  Install AWS CLI on a Linux host

inputs:
  version:
    description: |
       - 1=latest version of v1
       - 2=latest version of v2
       - #.#.#=specific version
    required: false
    default: '2'
  verbose:
    description: |
      Prints ls commands to see changes in the filesystem
    required: false
    default: 'false'
  lightsailctl:
    description: |
      Install lightsailctl plugin
    required: false
    default: 'false'
  arch:
    description: |
      Allowed values are
        - amd64
        - arm64
    required: false
    default: 'arm64'
  rootdir:
    description: |
      Root directory full path, defaults to PWD
    required: false
    default: ''
  workdir:
    description: |
      Working directory full path, all files
      are downloaded and extracted in this directory
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - uses: unfor19/install-aws-cli-action@7a427b852d87c231cb6a8ace7aff7317a6a37243
      with:
        version: ${{ inputs.version }}
        verbose: ${{ inputs.verbose }}
        lightsailctl: ${{ inputs.lightsailctl }}
        arch: ${{ inputs.arch }}
        rootdir: ${[ inputs.rootdir }}
        workdir: ${[ inputs.workdir }}
