name: Run shell script with action tests library
author: 'MiLaboratories'
description: |
  Run shell script with action tests library loaded

inputs:
  test:
    description: |
      Tests to run.
      This is a regular shell script with 'ghwa_commands' and 'testlib' libraries loaded.
      You can use test_* functions to perform checks

    required: true

runs:
  using: "composite"

  steps:
    - name: Run tests
      id: tests
      uses: milaboratory/github-ci/actions/shell@v4-beta
      with:
        dump-stdout: false
        run: |
          source "${{ github.action_path }}/testlib.sh"

          ${{ inputs.test }}

          _check_status
