name: Upload artifact's contents to S3 bucket
author: 'MiLaboratories'
description: |
  Upload artifact's contents to S3 Bucket.

  Requirements:
    - initialized context (actions/context/init)

inputs:
  artifact-name:
    description: |
      Name of artifact to work with. This artifact will be downloaded
      from GitHub, all its contents will be uploaded to S3.
    required: false
    default: ''
  artifact-override-os-arch:
    description: |
      For cross-compiled binaries, override the target
      architecture for the resulting archive name.

      For example, if we want to build an arm64 go binary
      by cross-compiling it on the amd64 machine, we need to override
      the resulted name of the archive, e.g., app-am64.zip to app-arm64.zip
      Because by default, we are using an architecture discovered from the os.
    required: false
    default: ''
  artifact-os-name:
    description: |
      Target os name for artifacts inside the archive. e.g., linux.
      This will be added to resulting json with detailed information
      about uploaded archives on s3.
    required: false
    default: ''
  add-version:
    description: |
      Add verison number to all uploaded files.
      If file in artifact has extension (e.g. 'app.zip')
      and current version (from actions/context) is, say, '1.3.0',
      the file in S3 would have name 'app-1.3.0.zip'.

      Files without extension ('myfile') will have version number
      appended ('myfile-1.3.0').
    required: false
    default: 'false'
  add-sha:
    description: |
      Add abbreviated commit SHA to uploaded files.
      If file in artifact has extension (e.g. 'app.zip')
      and current SHA is, say, 'deadfacea6c72ef99d5b11c67973a4b7d5109de9',
      the file in S3 would have name 'app-deadface.zip'.

      Files without extension ('myfile') will have version number
      appended ('myfile-deadface').

      If both 'add-version' and 'add-sha' are 'true', SHA is added to
      file name AFTER version number: app-1.2.3-deadbeef

    required: false
    default: 'false'
  add-os-arch:
    description: |
      Add agent's operating system architecture to uploaded files
      If a file in the artifact has an extension e.g 'app.zip' and the current ARCH is,
      for instance, 'amd64', the resulting file name will be: 'app-amd64.zip.'

      Files without extension ('myfile') will have
      os architecture appended ('myfile-amd64').

      If 'add-version' 'add-sha' and 'add-arch' are true, ARCH is added
      to the file name after the version and sha: 'app-1.2.3-deadbeef-amd64'

    required: false
    default: 'false'
  add-github-run-id:
    description: |
      Github Run ID is a unique number for each workflow run within a repository.
      This number does not change if you re-run the workflow run.

      Add github run id to uploaded files. If a file in the artifact has an extension
      e.g., 'app.zip' and the current Run ID is, for instance, '3475688987', the resulting
      file name will be: 'app-3475688987.zip'

      If 'add-version', 'add-sha', 'add-arch', and 'add-github-run-id' are true, Run ID is added
      to the file name after the version and sha, but before arch: 'app-1.2.3-deadbeef-3475688987-amd64'
    required: false
    default: 'false'

  s3-iam-role-to-assume:
    description: |
      The ARN of a IAM role to assume and configure the Actions environment with
      assumed role credentials.
    required: false
    default: ''

  s3-region:
    description: |
      AWS region with target S3 bucket
    required: false
    default: 'eu-central-1'
  s3-bucket:
    description: |
      Application archive target S3 bucket
    required: true
  s3-path:
    description: |
      Put artifact's files into given 'directory' in
      S3 bucket.

      Files will be uploaded to:
        's3://<s3-bucket>/<s3-path>/<file-name>'

    required: true

  alternative-urls:
    description: |
      Any S3 file with public access could be downloaded from special URL with
      bucket name and region:
        https://<bucket-name>.s3.<region>.amazonaws.com/<s3-path>

      These URLs are placed to action's outputs by default.

      <alternative-urls> allows to customize URLs for some of the paths by
      applying alternation rules:
        <path> -> <custom URL>

      Example:
        Rule
          ^/cdn/software/ -> https://cdn.milaboratory.com/software/
        will make action to generate URL to cdn.milaboratory.com for any
        file inside /cdn/software/ directory in S3 storage.

    required: false
    default: ''

outputs:
  uploaded:
    description: |
      Newline-separated list of S3 keys for uploaded files
      (without bucket and region name)
    value: ${{ steps.uploaded-list.outputs.stdout }}
  uploaded-json:
    description: |
      'uploaded' in JSON format
    value: ${{ steps.uploaded-json.outputs.result }}

  download:
    description: |
      Newline-separated list of download links for files in S3
    value: ${{ steps.download-list.outputs.result }}
  download-json:
    description: |
      'download' in JSON format
    value: ${{ steps.download-json.outputs.result }}

  artifacts-list-json:
    description: |
      List of artefacts in JSON format with detailed information:
      size, sha256, relative path on s3, arch, os
    value: ${{ steps.artifacts-list.outputs.stdout }}

runs:
  using: "composite"

  steps:
    - id: context
      uses: milaboratory/github-ci/actions/context@v4-beta

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.s3-iam-role-to-assume }}
        aws-region: ${{ inputs.s3-region }}

    - id: artifact-path
      uses: milaboratory/github-ci/actions/shell@v4-beta
      with:
        run: echo './release-artifact'

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.artifact-path.outputs.stdout }}

    - name: Add version
      if: inputs.add-version == 'true'
      uses: milaboratory/github-ci/actions/files/add-suffix@v4-beta
      with:
        paths: ${{ steps.artifact-path.outputs.stdout }}
        suffix: '-${{ steps.context.outputs.current-version }}'

    - name: Get SHA suffix
      id: sha
      if: inputs.add-sha != 'false' && inputs.add-sha != ''
      uses: milaboratory/github-ci/actions/shell@v4-beta
      env:
        ADD_SHA: ${{ inputs.add-sha }}
      with:
        run: |
          current_sha="${GITHUB_SHA}"

          if [ "${ADD_SHA}" != 'true' ] && [ "${ADD_SHA}" -gt 0 ] ; then
            # Abbreviate SHA size to given number of symbols
            current_sha="${current_sha:0:${ADD_SHA}}"
          fi

          echo "${current_sha}"

    - name: Add SHA
      if: steps.sha.outputs.stdout != ''
      uses: milaboratory/github-ci/actions/files/add-suffix@v4-beta
      with:
        paths: ${{ steps.artifact-path.outputs.stdout }}
        suffix: '-${{ steps.sha.outputs.stdout }}'

    - name: Add Github Run ID
      if: inputs.add-github-run-id == 'true'
      uses: milaboratory/github-ci/actions/files/add-suffix@v4-beta
      with:
        paths: ${{ steps.artifact-path.outputs.stdout }}
        suffix: '-${{ github.run_id }}'

    - name: Get ARCH
      id: os_arch
      if: inputs.add-os-arch == 'true'
      uses: milaboratory/github-ci/actions/shell@v4-beta
      env:
        OVERRIDE_ARCH: ${{ inputs.artifact-override-os-arch }}
      with:
        run: |
          if [ ! -z "${OVERRIDE_ARCH}" ];then
            _target_arch="${OVERRIDE_ARCH}"
          else
            _target_arch="$(uname -m)"
          fi

          case "${_target_arch}" in
          "arm64"|"aarch64") echo "arm64" ;;
          "amd64"|"x86_64"|"x86") echo "amd64" ;;
          *)
          echo "unknown arch: $_target_arch"
          exit 1
          ;;
          esac

    - name: Add ARCH
      if: steps.os_arch.outputs.stdout != ''
      uses: milaboratory/github-ci/actions/files/add-suffix@v4-beta
      with:
        paths: ${{ steps.artifact-path.outputs.stdout }}
        suffix: '-${{ steps.os_arch.outputs.stdout }}'

    - name: Upload files
      uses: milaboratory/github-ci/actions/shell@v4-beta
      with:
        run: |
          aws s3 cp --recursive \
          ${{ steps.artifact-path.outputs.stdout }}/ \
          s3://${{ inputs.s3-bucket }}/${{ inputs.s3-path }}

    - id: uploaded-list
      uses: milaboratory/github-ci/actions/shell@v4-beta
      env:
        ARTIFACT_PATH: ${{ steps.artifact-path.outputs.stdout }}
        S3_PATH: ${{ inputs.s3-path }}
        OS_NAME: ${{ inputs.artifact-os-name }}
        OS_ARCH: ${{ steps.os_arch.outputs.stdout }}
      with:
        run: |
          S3_PATH="${S3_PATH%/}" # trim trailing '/'
          S3_PATH="${S3_PATH#/}" # trim leading '/'

          file_infos=()
          file_paths=()

          cd "${ARTIFACT_PATH}"
          while read -r file_path; do
              trimmed_file_path=${file_path#./}
              full_path="/${S3_PATH}/${trimmed_file_path}"

              file_type="${trimmed_file_path##*.}"

              if [ "${RUNNER_OS}" == "macOS" ];then
                file_size=$(stat -f%z "$trimmed_file_path")
              else
                file_size=$(stat -c%s "$trimmed_file_path")
              fi

              if [ "${RUNNER_OS}" == "Windows" ];then
                sha256=$(sha256sum "$trimmed_file_path" | awk '{ print $1 }')
              else
                sha256=$(shasum -a 256 "$trimmed_file_path" | awk '{ print $1 }')
              fi

              file_infos+=("{\"path\": \"${full_path}\", \"file_size\": \"${file_size}\", \"sha256\": \"${sha256}\", \"type\": \"${file_type}\", \"arch\": \"${OS_ARCH}\", \"os\": \"${OS_NAME}\" }")
              file_paths+=("$full_path")
          done < <(find . -mindepth 1 -type f,l,p)

          json_array_infos=$(printf '%s\n' "${file_infos[@]}" | jq -s '.')
          array_paths=$(printf '%s\n' "${file_paths[@]}")

          ghwa_set_output json_array_infos "{\"artifacts\": $json_array_infos}"
          ghwa_set_output array_paths "${array_paths}"

    - id: uploaded-json
      uses: milaboratory/github-ci/actions/strings/json-list@v4-beta
      with:
        input: ${{ fromJSON(steps.uploaded-list.outputs.data).array_paths }}

    - id: download-list
      uses: milaboratory/github-ci/actions/strings/replace@v4-beta
      with:
        input: ${{ fromJSON(steps.uploaded-list.outputs.data).array_paths }}

        # Any public S3 object is accessible through special URL:
        #   https://<bucket-name>.s3.<region>.amazonaws.com/<s3-path>
        #
        # The last replace rule generates this default URL for
        # all S3 paths not handled by 'alternative-urls'.
        rules: |
          ${{ inputs.alternative-urls }}

          ^/ -> https://${{ inputs.s3-bucket }}.s3.${{ inputs.s3-region }}.amazonaws.com/

    - id: download-json
      uses: milaboratory/github-ci/actions/strings/json-list@v4-beta
      with:
        input: ${{ steps.download-list.outputs.result }}

    - id: artifacts-list
      uses: milaboratory/github-ci/actions/shell@v4-beta
      env:
        JSON_ARRAY: ${{ fromJSON(steps.uploaded-list.outputs.data).json_array_infos }}
      with:
        run: |
          echo "${JSON_ARRAY}"
