name: 'File Globber'
description: 'A GitHub Action to perform globbing operations to find files based on patterns.'
author: 'MiLaboratories'

inputs:
  patterns:
    description: 'Glob patterns to search for files.'
    required: true
  follow-symbolic-links:
    description: 'Indicates whether to follow symbolic links.'
    default: true
outputs:
  files:
    description: 'Newline-delimited string of matched file paths.'

runs:
  using: 'node20'
  main: 'dist/index.js'
