name: 'Slack: Publish Notification Block'
description: |
  Reusable workflow block for sending Slack notifications about publication status.

inputs:
  job-status:
    description: 'The status of the publication job (e.g., success, failure).'
    required: true
  slack-bot-token:
    description: 'Slack Bot Token.'
    required: true
  slack-channel:
    description: 'Slack channel name or ID.'
    required: true
  product-name:
    description: 'Name of the product that was published.'
    required: false
    default: ${{ github.repository }}
  product-type:
    description: 'Type of the published resource (e.g., library, package).'
    required: false
    default: 'library'
  repository-category:
    description: 'Repository category (e.g., dev, release).'
    required: false
    default: 'dev'
  repository-type:
    description: 'Type of repository (e.g., maven, npm, py).'
    required: false
    default: 'maven'
  packages:
    description: 'List of published packages in JSON format.'
    required: false
    default: '[]'
  search-tags:
    description: 'List of search tags for the notification.'
    required: false
    default: '[]'
  additional-info:
    description: 'Additional text to append to the message.'
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - id: context
      uses: milaboratory/github-ci/actions/context@v4

    - uses: milaboratory/github-ci/actions/shell@v4
      id: category
      env:
        IS_RELEASE: ${{ steps.context.outputs.is-release }}
      with:
        run: |
          if [ "${IS_RELEASE}" = "true" ]; then
            echo "release"
          else
            echo "dev"
          fi

    - id: json
      uses: milaboratory/github-ci/actions/shell@v4
      env:
        SEARCH_TAGS: ${{ inputs.search-tags }}
      with:
        dump-stdout: false
        run: |
          ghwa_set_output "search-tags" "${SEARCH_TAGS:-[]}"

    - id: job-status
      name: Merge publish job statuses
      uses: milaboratory/github-ci/actions/helpers/merge-status@v4
      with:
        statuses: ${{ inputs.job-status }}

    - uses: milaboratory/github-ci/actions/notify/slack/publish@v4-beta
      with:
        slack-bot-token: ${{ inputs.slack-bot-token }}
        slack-channel: ${{ inputs.slack-channel }}
        job-status: ${{ steps.job-status.outputs.status }}
        product-name: ${{ inputs.product-name }}
        product-type: ${{ inputs.product-type }}
        build-category: ${{ steps.category.outputs.stdout }}
        repository-category: ${{ inputs.repository-category }}
        repository-type: ${{ inputs.repository-type }}
        packages: ${{ inputs.packages }}
        search-tags: ${{ fromJSON(steps.json.outputs.data).search-tags }}
        additional-info: ${{ inputs.additional-info }}
