name: 'Slack: Review Required Notification Block'
description: |
  Reusable workflow block for sending Slack notifications about required reviews.

inputs:
  slack-bot-token:
    description: 'Slack Bot Token.'
    required: true
  slack-channel:
    description: 'Slack channel name or ID.'
    required: true
  message:
    description: 'Message to display in the notification.'
    required: true
  reviewers:
    description: 'List of reviewers to call for action (one per line).'
    required: true
  product-name:
    description: 'Name of the product that requires review.'
    required: false
    default: ${{ github.repository }}
  additional-info:
    description: 'Additional text to append to the message.'
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - id: context
      uses: milaboratory/github-ci/actions/context@v4-beta

    - uses: milaboratory/github-ci/actions/notify/slack/review-required@v4-beta
      with:
        slack-bot-token: ${{ inputs.slack-bot-token }}
        slack-channel: ${{ inputs.slack-channel }}
        message: ${{ inputs.message }}
        reviewers: ${{ inputs.reviewers }}
        product-name: ${{ inputs.product-name }}
        additional-info: ${{ inputs.additional-info }}
