name: Prepare environment for NodeJS PNPM
author: 'MiLaboratories'
description: |
  Prepare environment: install specific version of Node, restore cache for modules.

inputs:
  node-version:
    description: |
      Node version to use.
      Examples: '16.x', '14.x'
    required: true

  cache-version:
    description: |
      Simple hack, that allows to 'reset' cache for particular job.

      Just change the value of this parameter and the next run will
      not find build cache and will have to start from scratch.

    required: false
    default: 'v1'

  cache-enabled:
    description: |
      Enable npm github actions cache
    required: false
    default: 'true'

  pnpm-version:
    description: |
      Version of pnpm to install
    required: false
    default: 'latest'

  hashfiles-search-path:
    description: |
      Hashfiles search path for pnpm-lock.yaml
    required: false
    default: '**/pnpm-lock.yaml'

  registry-url:
    description: |
      The npm registry url to set up for auth
      and publication of the node js package.
    required: false
    default: 'https://npm.pkg.github.com'

  scope:
    description: |
      Scope for authenticating against npm registries.
    required: false
    default: ${{ format('{0}{1}', '@', github.repository_owner) }}

  always-auth:
    description: |
      Set always-auth in npmrc.
    required: false
    default: 'false'

  npmrc-config:
    description: |
      Generates a .npmrc file based on provided configuration.
    required: false

runs:
  using: "composite"

  steps:
    - name: Install NodeJS - ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        always-auth: ${{ inputs.always-auth }}

    - name: Re-Write .npmrc config
      uses: milaboratory/github-ci/actions/utils/create-npmrc@v4-beta
      if: inputs.npmrc-config != ''
      with:
        npmrcConfig: ${{ inputs.npmrc-config }}

    - name: Install pnpm - ${{ inputs.pnpm-version }}
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name:  Set up cache for a NodeJS PNPM application
      uses: milaboratory/github-ci/actions/node/cache-pnpm@v4-beta
      if: inputs.cache-enabled == 'true'
      with:
        hashfiles-search-path: ${{ inputs.hashfiles-search-path }}
        cache-version: ${{ inputs.cache-version }}