name: Add milaboratory apt repository
author: 'MiLaboratories'
description: |
  This actions adds Milaboratory APT S3 repository with special deb packages
  needed for building and running tests for the Platform on the Ubuntu/Debian GNU Linux.


inputs:
  aws-iam-role-to-assume:
    description: |
      The ARN of a IAM role to assume and configure the Actions environment with
      assumed role credentials.
    required: true
  aws-region:
    description: |
      The AWS region
    required: true
    default: 'eu-central-1'
  aws-s3-apt-repository-bucket-name:
    description: |
      AWS S3 APT repository bucket name
    required: true
    default: 'milab-euce1-prod-pkgs-s3-apt-repository'

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-iam-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - uses: milaboratory/github-ci/actions/shell@v4
      env:
        APT_REPO_S3_BUCKET_NAME: ${{ inputs.aws-s3-apt-repository-bucket-name }}
      with:
        dump-stdout: false
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-s3

          echo "deb [trusted=yes] s3://${APT_REPO_S3_BUCKET_NAME}/$(lsb_release -is | tr A-Z a-z)/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list > /dev/null

          # explicitly define the s3auth config because apt s3 transport
          # utility can't pick up aws region from environment variables.
          sudo bash -c "cat > /etc/apt/s3auth.conf" << EOF
          AccessKeyId = "${AWS_ACCESS_KEY_ID}"
          SecretAccessKey = "${AWS_SECRET_ACCESS_KEY}"
          Token = "${AWS_SESSION_TOKEN}"
          Region = "${AWS_REGION}"
          EOF

          sudo apt-get update