name: CodeSign Binary on macOS
author: "MiLaboratories"
description: |
  The CodeSign Binary Action is a GitHub Action designed to automate the process
  of signing software binaries on macOS using the codesign utility.
  This action ensures that the binary conforms to Apple's security requirements,
  making it suitable for distribution or deployment on macOS systems.

  Created based on https://github.com/ddev/signing_tools

inputs:
  binaries:
    description: |
      List of paths (one per line) to the binary files that need to be signed.
      Each line may be a globbing pattern, that is expanded into list of lines.
    required: true

  entitlements:
    description: |
      Add given entitlements into a signed code.
    required: false

  mac-cert-id:
    description: |
      The Apple's certificate id. e.g: '5MXXYYZZFF'
    required: true

  mac-cert-base64:
    description: |
      The base64-encoded p12 signing certificate.
    required: true

  mac-cert-passwd:
    description: |
      The password to decrypt the p12 signing certificate.
    required: true

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/files/list@v4-db-1
      id: binaries-list
      with:
        patterns: ${{ inputs.binaries }}
        relative: true
        match-directories: false

    - name: "Run CodeSign for Mac OS X"
      env:
        BINARIES: ${{ steps.binaries-list.outputs.paths }}
        ENTITLEMENTS: ${{ inputs.entitlements }}
        CERT_ID: ${{ inputs.mac-cert-id }}
        CERT_BASE64: ${{ inputs.mac-cert-base64 }}
        CERT_PWD: ${{ inputs.mac-cert-passwd }}
        CERT_FILE: ${{ format('{0}.p12', inputs.mac-cert-id) }}

        ACTION_SCRIPT_PATH: ${{ github.action_path }}/codesign.sh

      shell: bash
      run: "${ACTION_SCRIPT_PATH}"
