name: Track changed files
author: 'MiLaboratories'
description: |
  Get all Added, Copied, Modified, Deleted,
  Renamed, Type changed, Unmerged, Unknown files
  in git repository during workflow execution.
  
  See original action tj-actions/changed-files

inputs:
  separator:
    description: "Split character for output strings"
    required: false
    default: " "
  include_all_old_new_renamed_files:
    description: "Include `all_old_new_renamed_files` output. Note this can generate a large output See: [#501](https://github.com/tj-actions/changed-files/issues/501)."
    required: false
    default: "false"
  old_new_separator:
    description: "Split character for old and new filename pairs."
    required: false
    default: ","
  old_new_files_separator:
    description: "Split character for old and new renamed filename pairs."
    required: false
    default: " "
  files_from_source_file:
    description: "Source file(s) used to populate the `files` input."
    required: false
    default: ""
  files_from_source_file_separator:
    description: 'Separator used to split the `files_from_source_file` input'
    default: "\n"
    required: false
  files:
    description: "File and directory patterns to detect changes using only these list of file(s) (Defaults to the entire repo) **NOTE:** Multiline file/directory patterns should not include quotes."
    required: false
    default: ""
  files_separator:
    description: "Separator used to split the `files` input"
    default: "\n"
    required: false
  files_ignore:
    description: "Ignore changes to these file(s) **NOTE:** Multiline file/directory patterns should not include quotes."
    required: false
    default: ""
  files_ignore_separator:
    description: "Separator used to split the `files_ignore` input"
    default: "\n"
    required: false
  files_ignore_from_source_file:
    description: "Source file(s) used to populate the `files_ignore` input"
    required: false
    default: ""
  files_ignore_from_source_file_separator:
    description: 'Separator used to split the `files_ignore_from_source_file` input'
    default: "\n"
    required: false
  sha:
    description: "Specify a different commit SHA used for comparing changes"
    required: false
  base_sha:
    description: "Specify a different base commit SHA used for comparing changes"
    required: false
  since:
    description: "Get changed files for commits whose timestamp is older than the given time."
    required: false
    default: ""
  until:
    description: "Get changed files for commits whose timestamp is earlier than the given time."
    required: false
    default: ""
  path:
    description: "Specify a relative path under `$GITHUB_WORKSPACE` to locate the repository."
    required: false
    default: "."
  quotepath:
    description: "Use non ascii characters to match files and output the filenames completely verbatim by setting this to `false`"
    default: "true"
    required: false
  diff_relative:
    description: "Exclude changes outside the current directory and show path names relative to it. **NOTE:** This requires you to specify the top level directory via the `path` input."
    required: false
    default: "true"
  dir_names:
    default: "false"
    description: "Output unique changed directories instead of filenames. **NOTE:** This returns `.` for changed files located in the root of the project."
    required: false
  dir_names_max_depth:
    description: "Maximum depth of directories to output. e.g `test/test1/test2` with max depth of `2` returns `test/test1`."
    required: false
  dir_names_exclude_root:
    description: "Exclude the root directory represented by `.` from the output when `dir_names`is set to `true`."
    required: false
    default: "false"
  json:
    description: "Output list of changed files in a JSON formatted string which can be used for matrix jobs."
    required: false
    default: "false"
  escape_json:
    description: "Escape JSON output."
    required: false
    default: "true"
  fetch_depth:
    description: "Depth of additional branch history fetched. **NOTE**: This can be adjusted to resolve errors with insufficient history."
    required: false
    default: "50"
  since_last_remote_commit:
    description: "Use the last commit on the remote branch as the `base_sha`. Defaults to the last non merge commit on the target branch for pull request events and the previous remote commit of the current branch for push events."
    required: false
    default: "false"
  write_output_files:
    description: "Write outputs to files in the `.github/outputs` folder by default."
    required: false
    default: "false"
  output_dir:
    description: "Directory to store output files."
    required: false
    default: ".github/outputs"

runs:
  using: "composite"

  steps:
    - name: Changed Files
      uses: tj-actions/changed-files@043929ee8fffa1dd1d619782a5a338cf39e76e23
      with:
        separator: ${{ inputs.separator }}
        include_all_old_new_renamed_files: ${{ inputs.include_all_old_new_renamed_files }}
        old_new_separator: ${{ inputs.old_new_separator }}
        old_new_files_separator: ${{ inputs.old_new_files_separator }}
        files_from_source_file: ${{ inputs.files_from_source_file }}
        files_from_source_file_separator: ${{ inputs.files_from_source_file_separator }}
        files: ${{ inputs.files }}
        files_separator: ${{ inputs.files_separator }}
        files_ignore: ${{ inputs.files_ignore }}
        files_ignore_separator: ${{ inputs.files_ignore_separator }}
        files_ignore_from_source_file: ${{ inputs.files_ignore_from_source_file }}
        files_ignore_from_source_file_separator: ${{ inputs. files_ignore_from_source_file_separator }}
        sha: ${{ inputs.sha }}
        base_sha: ${{ inputs.base_sha }}
        since: ${{ inputs.since }}
        until: ${{ inputs.until }}
        path: ${{ inputs.path }}
        quotepath: ${{ inputs.quotepath }}
        diff_relative: ${{ inputs.diff_relative }}
        dir_names: ${{ inputs.dir_names }}
        dir_names_max_depth: ${{ inputs.dir_names_max_depth }}
        dir_names_exclude_root: ${{ inputs.dir_names_exclude_root }}
        json: ${{ inputs.json }}
        escape_json: ${{ inputs.escape_json }}
        fetch_depth: ${{ inputs.fetch_depth }}
        since_last_remote_commit: ${{ inputs.since_last_remote_commit }}
        write_output_files: ${{ inputs.write_output_files }}
        output_dir: ${{ inputs.output_dir }}
