name: Prepare environment for building a Python application
author: 'MiLaboratories'
description: |
  Prepare environment: install specific version of Python, restore cache for modules.

inputs:
  python-version:
    description: |
      Python version to use.
      Examples: '3.11', '3.12'
    required: true

  cache-version:
    description: |
      Simple hack, that allows to 'reset' cache for particular job.

      Just change the value of this parameter and the next run will
      not find build cache and will have to start from scratch.

    required: false
    default: 'v1'

  cache-hashfiles-search-path:
    description: |
      Hashfiles search path for requirements.txt
    required: false
    default: '**/requirements.txt'

runs:
  using: "composite"

  steps:
    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '${{ inputs.python-version }}'

    - name: Setup Cache for Python project
      uses: milaboratory/github-ci/actions/python/cache@v4-db-1
      with:
        version: ${{ inputs.cache-version }}
        hashfiles-search-path: ${{ inputs.cache-hashfiles-search-path }}
