name: Launch the Platforma container using Docker Compose
author: 'MiLaboratories'
description: |
  Launch the Platforma container using Docker Compose.

  Requirements:
    - get authorization token for aws ecr (aws-actions/amazon-ecr-login)

inputs:
  pl-docker-registry:
    description: |
      Platforma docker registry.
    required: false
    default: '511903394050.dkr.ecr.eu-central-1.amazonaws.com/pl'
  pl-docker-tag:
    description: |
      Platforma docker tag.
    required: false
    default: 'main'
  pl-sleep-time:
    description: |
      The waiting period after the Platforma starts.
    required: false
    default: '1'
  pl-test-assets-dir:
    description: |
      Platforma test assets directory;
      this directory will be mounted inside
      the container under the path `/storage/controllers/file/library`
      The path must be relative to github.workspace
      and will be appended to github.workspace within the docker compose action.
    required: false
    default: 'assets'
  pl-log-level:
    description: |
      Platforma log level
    required: false
    default: 'info'

outputs:
  main-root:
    description: 'Path to platforma main root directory'
    value: ${{ steps.launch-pl.outputs.main-root }}
  log-dir:
    description: 'Path to platforma log directory'
    value: ${{ steps.launch-pl.outputs.main-root }}/log
  db-dir:
    description: 'Path to platforma db directory'
    value: ${{ steps.launch-pl.outputs.main-root }}/rocksdb

runs:
  using: "composite"

  steps:
    - name: Install Docker Compose
      uses: milaboratory/github-ci/actions/shell@v4-beta

      with:
        run: |
          echo "Installing Docker Compose..."
          ARCH=$(uname -m)
          DOCKER_ARCH=""

          if [ "$ARCH" = "x86_64" ]; then
            DOCKER_ARCH="x86_64"
          elif [ "$ARCH" = "aarch64" ]; then
            DOCKER_ARCH="aarch64"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-${DOCKER_ARCH}" -o "$DOCKER_CONFIG/cli-plugins/docker-compose"
          chmod +x "$DOCKER_CONFIG/cli-plugins/docker-compose"
          docker compose version

    - name: Launch Platforma
      id: launch-pl
      shell: bash
      env:
        PL_DOCKER_REGISTRY: ${{ inputs.pl-docker-registry }}
        PL_DOCKER_TAG: ${{ inputs.pl-docker-tag }}
        PL_MAIN_ROOT: ${{ }}
        PL_TEST_ASSETS_DIR: ${{ format('{0}/{1}', github.workspace, inputs.pl-test-assets-dir) }}
        PL_LOG_LEVEL: ${{ inputs.pl-log-level }}
        PL_SLEEP_TIME: ${{ inputs.pl-sleep-time }}
        PL_WORKSPACE: ${{ github.workspace }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        # Just in case if there are no test assets in the repository
        mkdir -pv "${PL_TEST_ASSETS_DIR}"
        export TMPDIR="${PL_WORKSPACE}/tmp"
        mkdir -pv "${TMPDIR}"

        export MAIN_ROOT="$(mktemp -d)"
        echo "main-root=${MAIN_ROOT}" >> "${GITHUB_OUTPUT}"

        docker compose --file "${ACTION_PATH}/docker-compose.yaml" up --detach --force-recreate

        echo "Wait for the Platforma to start"
        sleep "${PL_SLEEP_TIME}"
