name: "platform"

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpassword
  platforma:
    image: ${PL_DOCKER_REGISTRY}:${PL_DOCKER_TAG}
    command: |
       --auth-htpasswd="/etc/htpasswd"
       --listen-address="0.0.0.0"
       --listen-port="6345"
       --log-dst="dir://storage/log"
       --log-level="${PL_LOG_LEVEL:-info}"
       --db-dir="/storage/rocksdb"
       --work-dir="/storage/controllers/data/work"
       --packages-dir="/storage/controllers/packageLoader"
       --primary-storage-s3="http://minio:9000/platforma-primary-bucket"
       --primary-storage-s3-key="static:testuser"
       --primary-storage-s3-secret="static:testpassword"
       --primary-storage-s3-external-endpoint="http://localhost:9000/"
       --data-library-fs="test-assets=/storage/controllers/data/library"
    ports:
      - "6345:6345"
    tmpfs: [ /tmp ]
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "4"
    environment:
      - "MI_LICENSE=${MI_LICENSE:-}"
      - "PL_LICENSE=${PL_LICENSE:-}"
      - "PL_DATA_CREATE_BUCKET=${PL_DATA_CREATE_BUCKET:-true}"
    volumes:
      - platforma-file-primary:/storage/controllers/data/primary
      - platforma-file-library:/storage/controllers/data/library
      - platforma-file-work:/storage/controllers/data/work
      - platforma-packages:/storage/controllers/packageLoader
      - platforma-db:/storage/rocksdb
      - platforma-log:/storage/log
      - platforma-license:/storage/license
      - platforma-workspace:${PL_WORKSPACE}
      - ${ACTION_PATH}/htpasswd:/etc/htpasswd
    restart: always

volumes:
  platforma-packages:
  platforma-file-work:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_WORK_DIR}
  platforma-file-primary:
  platforma-file-library:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_TEST_ASSETS_DIR}
  platforma-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_DB_DIR}
  platforma-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_LOG_DIR}
  platforma-license:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_LICENSE_DIR:-}
  platforma-workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_WORKSPACE}