name: "platform"

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpassword

  platforma:
    image: ${PL_DOCKER_REGISTRY}:${PL_DOCKER_TAG}
    ports:
      - ${PL_API_PORT:-6345}:${PL_API_PORT:-6345}
    tmpfs: [ /tmp ]

    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "4"

    environment:
      - "MI_LICENSE=${MI_LICENSE:-}"
      - "PL_LICENSE=${PL_LICENSE:-}"
      - "PL_LICENSE_FILE=${PL_LICENSE_FILE:+/storage/license/${PL_LICENSE_FILE}}"
      - "PL_API_ADDR=0.0.0.0:${PL_API_PORT:-6345}"
      - "PL_LOG_LEVEL=${PL_LOG_LEVEL:-info}"
      - "PL_LOG_DESTINATION=${PL_LOG_DESTINATION:-stdout}"
      - "PL_LOG_COMMIT_SUMMARY=${PL_LOG_COMMIT_SUMMARY:-false}"
      - "PL_LOG_RESOURCE_DATA=${PL_LOG_RESOURCE_DATA:-false}"
      - "PL_AUTH_ENABLED=${PL_AUTH_ENABLED:-false}"
      - "PL_DUMP_CONFIG_BEFORE_RUN=yes"
      - "PLC_FILE_PRIMARY_S3_ENDPOINT=http://minio:9000/"
      - "PLC_FILE_PRIMARY_S3_KEY=static:testuser"
      - "PLC_FILE_PRIMARY_S3_SECRET=static:testpassword"
      - "PLC_FILE_PRIMARY_S3_PRESIGN_ENDPOINT=${PLC_FILE_PRIMARY_S3_PRESIGN_ENDPOINT:-http://localhost:9000}"
    volumes:
      - pl_test_assets:/storage/controllers/file/library
      - pl_log:/storage/log
      - pl_license:/storage/license

    restart: always

volumes:
  host_tmp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TMPDIR:-/tmp}

  pl_test_assets:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_TEST_ASSETS_DIR}

  pl_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_LOG_DIR}

  pl_license:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PL_LICENSE_DIR:-}