name: Cache NodeJS PNPM
author: 'MiLaboratories'
description: |
  Cache NodeJS modules when using pnpm.

inputs:
  cache-version:
    description: |
      Simple hack, that allows to 'reset' cache for particular job.

      Just change the value of this parameter and the next run will
      not find build cache and will have to start from scratch.

    required: false
    default: 'v1'

  cache-hashfiles-search-path:
    description: |
      Hashfiles search path for pnpm-lock.yaml
    required: false
    default: '**/pnpm-lock.yaml'

runs:
  using: "composite"

  steps:
    - name: Get pnpm store path
      id: pnpm-store-dir
      shell: bash
      run: echo "dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}

    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.pnpm-store-dir.outputs.dir }}
          ~/.pnpm-store
        key: ${{ runner.os }}-${{ runner.arch }}-cache-pnpm-${{ inputs.cache-version }}-genericnodejs-${{ hashFiles(inputs.cache-hashfiles-search-path) }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-cache-pnpm-${{ inputs.cache-version }}-genericnodejs-