name: Notify about failed release
description: |
  Notify User or Channel about failed release

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was built
    required: false
    default: ${{ github.repository }}
  version:
    description: |
      Release version number
    required: true
  tag:
    description: |
      Release tag
    required: true

  search-tags:
    description: |
      List of search tags for the telegram notification channel
    required: false
    default: '[]'

  additional-info:
    description: |
      Additional text to append to message
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - id: safe-ctx
      uses: milaboratory/github-ci/actions/helpers/safe-ctx@v4-db-1

    - uses: milaboratory/github-ci/actions/templates/jinja@v4-db-1
      id: message
      with:
        data: |
          { "product": { "name": ${{ toJSON(inputs.product-name) }},
                         "additional_info": ${{ toJSON(inputs.additional-info) }} },

            "release": { "version": ${{ toJSON(inputs.version) }},
                         "tag": ${{ toJSON(inputs.tag) }} },

            "github": ${{ steps.safe-ctx.outputs.github }},

            "search_tags": ${{ inputs.search-tags }}
          }

        template: |
          ☠️ \[{{ product["name"] }}] Release failed! :(
            Version: {{ release["version"] }}
            Tag: {{ release["tag"] }}
          \[ [Source code](
            {{- github["server_url"] }}/{{ github["repository"] }}/tree/{{ github["sha"] -}}
          ) | [CI logs](
            {{- github["server_url"] }}/{{ github["repository"] }}/actions/runs/{{ github["run_id"] -}}
          ) ]

          {%- if product["additional_info"] | length > 0 %}
          Additional info:
            {{ product["additional_info"] }}
          {%- endif %}
          Tags: #{{- github["event"]["repository"]["name"] | replace("-", "_") | replace(".", "_") -}} {%- if search_tags | length > 0 %}{% for i in search_tags  %} #{{ i | replace("-", "_") | replace("/", "_") }} {% endfor %}{%- endif %}

    - uses: milaboratory/github-ci/actions/notify/telegram/send@v4-db-1
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        disable_web_page_preview: true
        message: ${{ steps.message.outputs.data }}
