name: 'Matrix outputs - read'
author: 'MiLaboratories'
description: |
  Read outputs for github actions matrix
  See original action cloudposse/github-action-matrix-outputs-write

inputs:
  matrix-step-name:
    description: "Matrix step name"
    required: true
outputs:
  result:
    description: "Outputs result"
    value: ${{ steps.context.outputs.result }}

runs:
  using: "composite"

  steps:
    - uses: actions/download-artifact@v3

    - id: context
      shell: bash
      run: |
        result="$(find . -name ${{ inputs.matrix-step-name }} -maxdepth 2 -exec cat {} \; | jq -c --slurp 'map(to_entries | map(.key as $matrix_key | .value | map_values({($matrix_key): .}))) | flatten | reduce .[] as $item ({}; . * $item)' )"
        echo "result=${result}" >> $GITHUB_OUTPUT