name: Check artifact existence
author: 'MiLaboratories'
description: |
  Check existence of an artifact uploaded in the workflow by the upload-artifact action
  See original action LIT-Protocol/artifact-exists-action

inputs:
  name:
    description: 'Artifact name'
    required: true
outputs:
  exists:
    description: 'Boolean indicating that artifact exist'
    value: ${{ steps.check.outputs.exists }}

runs:
  using: "composite"

  steps:
    - name: Check artifact existence
      id: check
      uses: LIT-Protocol/artifact-exists-action@ff41b0e92208918c585721cbf3e866dfddaf7879
      with:
        name: ${{ inputs.name }}
