name: Authenticate in the Github private repository
author: 'MiLaboratories'
description: |
  This actions sets authentication header with base64 encoded github token in the git config

inputs:
  github-token:
    description: |
      Github token to authorize git operation in the same repository as the workflow.
    required: true
  github-url-rewrite:
    description: |
      Rewrite URLs for a Git operation. Substitute git@github.com with https://github.com.
      And substitute ssh:// with https://
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: milaboratory/github-ci/actions/shell@v4
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_URL_REWRITE: ${{ inputs.github-url-rewrite }}
      with:
        run: |
          BASE64_ENCODED=$(printf "%s" "x-access-token:${GH_TOKEN}" | base64)
          echo "Set auth header."
          git config --global http."https://github.com/".extraHeader "AUTHORIZATION: basic ${BASE64_ENCODED}"

          if [ "${GH_URL_REWRITE}" == 'true' ];then
            echo "Set url rewrite config."
            git config --global url."https://github.com/".insteadOf git@github.com:
            git config --global url."https://".insteadOf ssh://
          fi