name: Safe context
description: |
  Reads file with valid JSON object and produces it as output,
  so caller can access it through <step>.outputs.v.<some key from JSON file>
  This is the convenient way to guide CI through structured data inside
  file in repository

inputs:
  file:
    description: |
      Path to file to read
    required: true

outputs:
  v:
    description: |
      JSON-encoded {{ github }} context with .token removed
    value: ${{ steps.readJSON.outputs.data }}

runs:
  using: "composite"

  steps:
    - id: readJSON
      uses: milaboratory/github-ci/actions/shell@v4-beta
      env:
        INPUT_FILE: ${{ inputs.file }}
      with:
        dump-stdout: false
        run: |
          ghwa_set_output "json" "$(cat "${INPUT_FILE}")"
