name: Read Gradle project properties
author: 'MiLaboratories'
description: |
  Read all gradle project properties and export them as outputs

inputs:
  project-dir:
    description: |
      Gradle project root (with settings.gradle file)
    required: false
    default: ./

  project-name:
    description: |
      Project to get properties (gradle :<project>:properties)
    required: false
    default: ''

  #
  # Cache gradle control
  #
  cache-read-only:
    description: |
      When 'true', existing entries will be read from the cache but no entries will be written.
      By default this value is 'false' for workflows on the GitHub default branch and 'true' for workflows on other branches.
    required: false
    default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}
  cache-write-only:
    description: |
      When 'true', entries will not be restored from the cache but will be saved at the end of the Job.
      Setting this to 'true' implies cache-read-only will be 'false'.
    required: false
    default: 'false'
  gradle-home-cache-includes:
    description: Paths within Gradle User Home to cache.
    required: false
    default: |
      caches
      notifications
  gradle-home-cache-excludes:
    description: Paths within Gradle User Home to exclude from cache.
    required: false


# Feel free to add more properties here.
# The underlying script supports all properties by default, but there is no way to pass
# 'all' properties to action's outputs.
# We have to explicitly list props to be provided in action's outputs.
outputs:
  name:
    description: name property
    value: ${{ steps.props.outputs.name }}

  group:
    description: group property
    value: ${{ steps.props.outputs.group }}

  version:
    description: version property
    value: ${{ steps.props.outputs.version }}

  buildDir:
    description: buildDir property
    value: ${{ steps.props.outputs.buildDir }}

runs:
  using: "composite"

  steps:
    - uses: milaboratory/github-ci/actions/java/gradle/gradlew@v4
      with:
        build-root-directory: ${{ inputs.project-dir }}
        gradle-home-cache-includes: ${{ inputs.gradle-home-cache-includes }}
        gradle-home-cache-excludes: ${{ inputs.gradle-home-cache-excludes }}
        cache-read-only: ${{ inputs.cache-read-only }}
        cache-write-only: ${{ inputs.cache-write-only }}

    - name: Read and print properties
      id: props
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      env:
        ACTION_PATH: ${{ github.action_path }}
        TASK_PREFIX: ${{ inputs.project-name && format(':{0}:', inputs.project-name) || ':' }}

      run: |
        ./gradlew --quiet "${TASK_PREFIX}properties" |
          "${ACTION_PATH}/dump-props.sh"
