name: MiLab various shell utilities
author: 'MiLaboratories'
description: |
  Add to PATH various MiLaboratories shell utilities.

runs:
  using: "composite"

  steps:
    - name: Add script to PATH
      shell: bash
      run: echo "${{ github.action_path }}/bin" >> $GITHUB_PATH