name: Setup CCache tool
author: 'MiLaboratories'
description: |
  Installs ccache tool and customizes its configuration.

inputs:
  options:
    description: |
      List of configuration options to pass to ccache.
      Each option should be specified as a key-value pair, one per line.
      For example:
        max_size=10.0G
        hash_dir=false
    required: false
    default: ''

  #
  # Options from original ccache-action
  #
  key:
    description: "An additional key for the cache"
    default: '${{ runner.os }}-${{ runner.arch }}'
    required: false

  restore-keys:
    description: "An ordered list of keys to use for restoring the cache if no cache hit occurred for key"
    default: |
      ${{ runner.os }}-${{ runner.arch }}
      ${{ runner.os }}
    required: false

  restore:
    description: "Flag for if you should restore cache or not, useful for generating clean cache."
    default: 'true'
    required: false

  max-size:
    description: "Max size of the cache"
    default: "500M"

  verbose:
    description: "Verbosity level: 0 (default), 1 or 2. Ignore for sccache."
    default: '0'

  variant:
    description: 'Ccache variant to use. Either "ccache" (the default) or "sccache" (see https://github.com/mozilla/sccache)'
    default: ccache

  save:
    description: "If 'false', do not save the cache, only restore."
    default: 'true'

  append-timestamp:
    description: "Append a timestamp to the cache key (default: true)"
    default: 'true'
    required: false

  create-symlink:
    description: "If set to 'true', create symlinks for ccache in /usr/local/bin to override default toolchains"
    default: 'false'
    required: false

  job-summary:
    description: "Publish stats as part of the job summary. Set to the title of the job summary section, or to the
     empty string to disable this feature. Requires CCache 4.10+"
    default: 'CCache Statistics'

  evict-old-files:
    description: "Corresponds to the ccache --evict-older-than AGE option, where AGE is the number of seconds or days
      followed by the 's' or 'd' suffix respectively. Also supports the special value 'job' which represents the time
      since the job started, which evicts all cache files that were not touched during the job run."
    default: ''

runs:
  using: "composite"

  steps:
    # The hendrikmuhs/ccache-action tries to install ccache automatically with apt-get,
    # which is not available on Rocky Linux.
    # Let action to support Rocky Linux by installing ccache manually.
    - name: Install ccache
      shell: bash
      run: |
        if [[ "$ImageOS" == rocky* ]]; then
          echo "Installing ccache for Rocky Linux"
          sudo dnf install -y ccache
        fi

    - name: Enable ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
        restore: ${{ inputs.restore }}
        max-size: ${{ inputs.max-size }}
        verbose: ${{ inputs.verbose }}
        variant: ${{ inputs.variant }}
        save: ${{ inputs.save }}
        append-timestamp: ${{ inputs.append-timestamp }}
        create-symlink: ${{ inputs.create-symlink }}
        job-summary: ${{ inputs.job-summary }}
        evict-old-files: ${{ inputs.evict-old-files }}

    - name: Configure ccache
      uses: milaboratory/github-ci/actions/shell@v4-beta
      env:
        OPTS: ${{ inputs.options }}
      with:
        run: |
          while read -r _opt; do
            if [ -z "$_opt" ]; then
              continue
            fi

            ccache --set-config $_opt
          done <<< "$OPTS"
