name: 'Create .npmrc File'
description: 'Generates a .npmrc file based on provided configuration'
author: 'MiLaboratories'

inputs:
  npmrcConfig:
    description: |
      JSON string with registry and scope settings. See example below.
      {
      "registries": {
        "https://registry.npmjs.org/": {
          "scopes": ["scope1", "scope2"],
          "tokenVar": "NPMJS_TOKEN"
        },
        "https://custom.npm.registry.com/": {
          "scopes": ["scope3"],
          "tokenVar": "NODE_AUTH_TOKEN"
        }
       }
      }
    required: true
  append:
    description: 'Whether to append to .npmrc instead of overwriting.'
    required: false
    default: 'false'
outputs:
  npmrcPath:
    description: 'The path to the created .npmrc file.'

runs:
  using: 'node20'
  main: 'dist/index.js'
