name: 'Create .npmrc File'
description: 'Generates a .npmrc.'
author: 'MiLaboratories'

inputs:
  npmrcConfig:
    description: |
      JSON string with registry and scope settings. See example below.
      
      {
        "registries": {
          "https://registry.npmjs.org/": {
            "scope1": "TOKEN_FOR_NPMJS"
          },
          "https://custom.npm.registry.com/": {
            "scope2": "SCOPE2_TOKEN",
            "scope3": "SCOPE3_TOKEN"
          },
          "https://another.registry.com/": {
            "scope4": "SCOPE4_TOKEN"
          }
        }
      }
    required: true
outputs:
  npmrcPath:
    description: 'The path to the created .npmrc file.'

runs:
  using: 'node20'
  main: 'dist/index.js'
