name: Telegram Message
description: |
  Notify User or Channel about changes in regression tests

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was built
    required: false
    default: ${{ github.repository }}
  build-version:
    description: |
      Build version to display in message
    required: true

  pull-request-url:
    description: |
      Pull request URL with changes
    required: false
    default: ''

  pull-request-number:
    description: |
      Pull request number
    required: false
    default: ''

  search-tags:
    description: |
      List of search tags for the telegram notification channel
    required: false
    default: '[]'

  additional-info:
    description: |
      Additional text to append to message
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - id: safe-ctx
      uses: milaboratory/github-ci/actions/helpers/safe-ctx@v4

    - uses: milaboratory/github-ci/actions/templates/jinja@v4
      id: message
      with:
        data: |
          { "product": { "name": ${{ toJSON(inputs.product-name) }},
                         "additional_info": ${{ toJSON(inputs.additional-info) }} },

            "build": { "version": ${{ toJSON(inputs.build-version) }} },

            "pull_request": {  "number": ${{ toJSON(inputs.pull-request-number) }},
                      "url": ${{ toJSON(inputs.pull-request-url) }} },

            "github": ${{ steps.safe-ctx.outputs.github }},

            "search_tags": ${{ inputs.search-tags }}
          }

        template: |
          🅰️ \[{{ product["name"] }}] Regression tests changes have been detected {{ '`' + build["version"] + '`' | string }}.
          Pull request:
            - {{ pull_request["url"] }}

          {%- if product["additional_info"] | length > 0 %}
          Additional info:
            {{ product["additional_info"] }}
          {%- endif %}
          \[ [Source code](
            {{- github["server_url"] }}/{{ github["repository"] }}/tree/{{ github["sha"] -}}
          ) | [CI logs](
            {{- github["server_url"] }}/{{ github["repository"] }}/actions/runs/{{ github["run_id"] -}}
          ) ]
          Tags: #{{- github["event"]["repository"]["name"] | replace("-", "_") | replace(".", "_") -}} {%- if search_tags | length > 0 %}{% for i in search_tags  %} #{{ i | replace("-", "_") | replace("/", "_") }} {% endfor %}{%- endif %}

    - uses: milaboratory/github-ci/actions/notify/telegram/send@v4
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        disable_web_page_preview: true
        message: ${{ steps.message.outputs.data }}