name: Telegram Message
description: |
  Notify User or Channel about changes in regression tests

inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was built
    required: false
    default: ${{ github.repository }}
  build-version:
    description: |
      Build version to display in message
    required: true

  pull-request-url:
    description: |
      Pull request URL with changes
    required: false
    default: ''

  pull-request-number:
    description: |
      Pull request number
    required: false
    default: ''

  additional-info:
    description: |
      Additional text to append to message
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - id: safe-ctx
      uses: milaboratory/github-ci/actions/helpers/safe-ctx@v4-beta

    - uses: milaboratory/github-ci/actions/templates/jinja@v4-beta
      id: message
      with:
        data: |
          { "product": { "name": ${{ toJSON(inputs.product-name) }},
                         "additional_info": ${{ toJSON(inputs.additional-info) }} },

            "build": { "version": ${{ toJSON(inputs.build-version) }} },

            "pull_request": {  "number": ${{ toJSON(inputs.pull-request-number) }},
                      "url": ${{ toJSON(inputs.pull-request-url) }} },

            "github": ${{ steps.safe-ctx.outputs.github }}

        template: |
          🅰️ \[{{ product["name"] }}] regression tests changes have been detected {{ build["version"] }}.
          Pull request:
            - {{- pull_request["url"] -}}
          \[ [Source code](
            {{- github["server_url"] }}/{{ github["repository"] }}/tree/{{ github["sha"] -}}
          ) | [CI logs](
            {{- github["server_url"] }}/{{ github["repository"] }}/actions/runs/{{ github["run_id"] -}}
          ) ]

          {{ product["additional_info"] }}

    - uses: milaboratory/github-ci/actions/notify/telegram/send@v4-beta
      with:
        to: ${{ inputs.telegram-target }}
        token: ${{ inputs.telegram-token }}
        format: markdown
        disable_web_page_preview: true
        message: ${{ steps.message.outputs.data }}