name: 'Build Electron application'
description: |
  Compile and release Electron appication.

inputs:
   build-version:
    description: |
       Set version number in 'package.json' file to given value.
    type: string
    required: false
  build-script-name:
    description: |
      Name of script for application build
    type: string
    required: true
    default: 'build'
  build-max-attempts:
    description: |
      Maximum number of attempts for completing the build and release step
    type: string
    required: false
    default: '1'
  build-package-root:
    description: Directory where NPM/Yarn commands should be run
    required: false
    default: '.'
  skip-build:
    description: Whether the action should execute the NPM build script before running `electron-builder`
    required: false
    default: false
  electron-build-args:
    description: |
      Other arguments to pass to the `electron-builder` command, e.g. configuration overrides
    type: string
    required: false
    default: ''
  is-vue-project:
    description: |
      This is vue-based project. Use 'vue-cli' toolkit
    type: boolean
    required: false
    default: false
  is-release:
    description: |
      Set If you would like to mark the current version as a release version.
    type: boolean
    required: false
    default: false
  token:
    description: |
      Copy "github_token" input variable to "GH_TOKEN" env variable (required by 'electron-builder')
    type: string
    required: true
  mac_sign_cert:
    description: |
      base64-encoded p12 certificate file for the macOS
    required: false
  mac_sign_cert_pwd:
    description: |
      password to decrypt the p12 signing certificate for the macOS
    required: false
  win_sign_cert:
    description: |
      base64-encoded p12 certificate file for the Windows
    required: false
  win_sign_cert_pwd:
    description: |
      password to decrypt the p12 signing certificate for the Windows
    required: false


runs:
  using: "composite"

  steps:
    - uses: samuelmeuli/action-electron-builder@e4b12cd06ddf023422f1ac4e39632bd76f6e6928
      env:
        VITE_APP_VERSION: ${{ inputs.build-version }}
      with:
        build_script_name: ${{ inputs.build-script-name }}
        args: ${{ inputs.electron-build-args }}
        release: ${{ inputs.is-release }}
        github_token: ${{ inputs.token }}

        package_root: ${{ inputs.build-package-root }}
        skip_build: ${{ inputs.skip-build }}
        use_vue_cli: ${{ inputs.is-vue-project }}
        max_attempts: ${{ inputs.build-max-attempts }}

        mac_certs: ${{ inputs.mac_sign_cert }}
        mac_certs_password: ${{ inputs.mac_sign_cert_pwd }}
        windows_certs: ${{ inputs.win_sign_cert }}
        windows_certs_password: ${{ inputs.win_sign_cert_pwd }}
