name: 'Matrix outputs - write'
author: 'MiLaboratories'
description: |
  Write outputs for github actions matrix
  See original action cloudposse/github-action-matrix-outputs-write

inputs:
  matrix-step-name:
    description: "Matrix step name"
    required: false
  matrix-key:
    description: "Matrix key"
    required: false
  outputs:
    description: "YAML structured map of outputs"
    required: false

runs:
  using: "composite"

  steps:
    - name: Write matrix output
      id: matrix-output-write
      uses: cloudposse/github-action-matrix-outputs-write@1326f1114208ee82052fdd48cd8ad97c21ae9dc0
      with:
        matrix-step-name: ${{ inputs.matrix-step-name }}
        matrix-key: ${{ inputs.matrix-key }}
        outputs: ${{ inputs.outputs }}
