name: Restore artifact, saved with actions/artifact/save
author: "MiLaboratories"
description: |
  Restore the artifact saved with actions/artifact/save. No path transforations are
  performed: the contents of artifact are restored like the data was initially created
  on current agent, keeping all permissions and paths (relative to current WD)

inputs:
    name:
      description: |
        Name of the artifact to download.
      required: true

    github-token:
      description: |
        The GitHub token used to authenticate with the GitHub API.
        This is required when downloading artifacts from a different repository or from a different workflow run.
        Optional. If unspecified, the action will download artifacts from the current repo and the current workflow run.
      required: false

    repository:
      description: |
        The repository owner and the repository name joined together by "/".
        If github-token is specified, this is the repository that artifacts will be downloaded from.
        Optional. Default is {{ github.repository }}
      required: false

    run-id:
      description: |
        The id of the workflow run where the desired download artifact was uploaded from.
        If github-token is specified, this is the run that artifacts will be downloaded from.
        Optional. Default is {{ github.run_id }}
      required: false

runs:
  using: "composite"

  steps:
    - name: Generate archive name
      id: archive-name
      shell: bash
      env:
        ARTIFACT_NAME: ${{ inputs.name }}
      run: |
        # We need unique archive name here to not overwrite any existing file in workdir.
        # We also need static name to simplify 'restore' action logic.
        # This name is an attempt to meet both criteria.
        archive_name="artifact-$( echo "${ARTIFACT_NAME}" | sha256sum | awk '{print $1}' )"
        echo "name=${archive_name}" >> "${GITHUB_OUTPUT}"

    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.name }}
        github-token: ${{ inputs.github-token }}
        repository: ${{ inputs.repository }}
        run-id: ${{ inputs.run-id }}

    - uses: fawazahmed0/action-debug-vscode@main
      env:
        ARCHIVE_NAME: ${{ steps.archive-name.outputs.name }}

    - name: Extract tar
      shell: bash
      env:
        ARCHIVE_NAME: ${{ steps.archive-name.outputs.name }}
      run: |
        tar -x -f "${ARCHIVE_NAME}.tar"
