name: Send notification about changes in regression tests
description: |
  Send notification about changes in regression tests

  Requirements:
      - initialized context (actions/context/init)
inputs:
  telegram-target:
    description: |
      Target telegram User or Channel ID
    required: true
  telegram-token:
    description: |
      Telegram Bot token
    required: true

  product-name:
    description: |
      Name of product that was built
    required: false
    default: ${{ github.repository }}
  build-version:
    description: |
      Build version to display in message
    required: true

  pull-request-url:
    description: |
      Pull request URL with changes
    required: false
    default: ''

  pull-request-number:
    description: |
      Pull request number
    required: false
    default: ''

  additional-info:
    description: |
      Additional text to append to message
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - id: context
      uses: milaboratory/github-ci/actions/context@v4-beta

    - uses: milaboratory/github-ci/actions/notify/telegram/tests@v4-beta
      with:
        telegram-target: ${{ inputs.telegram-target }}
        telegram-token: ${{ inputs.telegram-token }}

        product-name: ${{ inputs.product-name }}
        build-version: ${{ steps.context.outputs.current-version }}
        pull-request-url: ${{ inputs.pull-request-url }}
        pull-request-number: ${{ inputs.pull-request-number }}

        additional-info: ${{ inputs.additional-info }}