# This workflow is never used by any external repository.
# It is created solely for testing purposes when developing new actions.
# Feel free to change it however you want.
name: "Scan containers"

on:
  workflow_call:
  push:
    paths:
      - '.github/workflows/0-scan-containers.yaml'
      - 'actions/docker/scan-docker-repo/**'
    branches: [ 'v4-beta' ]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/docker/scan-docker-repo@v4-beta
        id: plan
        with:
          mode: plan
          report-name: "skipped-images"

          registry: containers.pl-open.science
          repository: milaboratories/pl-containers
          concurrency: 100

      - uses: actions/upload-artifact@v4
        with:
          name: scanning-plan
          path: ${{ steps.plan.outputs.plan-dir }}

    outputs:
      plan-dir: ${{ steps.plan.outputs.plan-dir }}
      plan-matrix: ${{ steps.plan.outputs.plan-matrix }}

  scan:
    runs-on: ubuntu-latest
    name: scan ${{ matrix.plan-file }}
    needs: plan
    strategy:
      matrix:
        include: ${{ fromJSON(needs.plan.outputs.plan-matrix) }}

    steps:
      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: scanning-plan
          path: "scan-chunks"

      - shell: bash
        run: |
          # Random sleep to avoid limiting on trivy side
          sl=$((RANDOM % 10))
          sleep ${sl}

      - uses: milaboratory/github-ci/actions/docker/scan-docker-repo@v4-beta
        with:
          mode: scan
          report-name: "trivy-report-${{ matrix.plan-file }}"
          tag-file: scan-chunks/${{ matrix.plan-file }}
