# This workflow is never used by any external repository.
# It is created solely for testing purposes when developing new actions.
# Feel free to change it however you want.
name: "Test"

on:
  workflow_call:
  push:
    paths:
      - '.github/workflows/0-test.yaml'
      - 'actions/post/artifact/'
    branches: [ 'v4', 'v4-beta' ]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          mkdir -p test-dir
          echo "Test 1 file content" > test-dir/test1.txt
          echo "Test 2 file content" > test-dir/test2.txt

      - uses: ./actions/post/artifact
        with:
          name: test
          path: |
            test-dir
