# This workflow is never used by any external repository.
# It is created solely for testing purposes when developing new actions.
# Feel free to change it however you want.
name: "Test"

on:
  workflow_call:
  push:
    paths:
      - '.github/workflows/0-test.yaml'
      - 'actions/post/artifact/**'
    branches: [ 'v4', 'v4-beta' ]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - shell: bash
        id: create-files
        run: |
          pwd

          mkdir -p test-dir
          echo "Test 1 file content" > test-dir/test1.txt
          echo "Test 2 file content" > test-dir/test2.txt

          mkdir -p test-dir2
          echo "Test 3 file content" > test-dir2/test3.txt

          find $(pwd)

          echo "root=$(pwd)" >> "${GITHUB_OUTPUT}"

      - uses: ./actions/post/artifact
        with:
          name: test-direct
          path: |
            test-dir
            ${{ steps.create-files.outputs.root }}/test-dir2

      - uses: ./actions/post/artifact
        with:
          name: test-archive
          archive: true
          path: |
            test-dir
            ${{ steps.create-files.outputs.root }}/test-dir2
