name: "Test"

on:
  push:
    branches: [ 'v4-beta' ]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          echo "Hello, world!" > test.txt

      - uses: ./actions/post/artifact
        with:
          name: test
          path: |
            test.txt
